/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gt.edu.umg.sistema.estudiantes.vista;

import gt.edu.umg.sistema.estudiantes.dao.FacturaDAOImpl;
import gt.edu.umg.sistema.estudiantes.modelo.Factura;

/**
 *
 * @author Aramis Ramos
 */
public class FrmFactura extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmFactura.class.getName());

    /**
     * Creates new form FrmFactura
     */
    public FrmFactura() {
        initComponents();
        
        // Cargar fecha actual automáticamente
        java.time.LocalDate fechaActual = java.time.LocalDate.now();
        java.time.format.DateTimeFormatter formato = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
        lblFecha.setText("Fecha: " + fechaActual.format(formato));
        
        javax.swing.table.DefaultTableModel modeloTabla = new javax.swing.table.DefaultTableModel();
        modeloTabla.addColumn("Descripción");
        modeloTabla.addColumn("Cantidad");
        modeloTabla.addColumn("Precio U.");
        modeloTabla.addColumn("Subtotal");
        jTable2.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        BtnAgregar = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        BtnRegresar = new javax.swing.JButton();
        lblTotalGeneral = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BtnEliminar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Módulo de Facturación");

        jLabel2.setText("NIT");

        txtNit.setText("\n");
        txtNit.addActionListener(this::txtNitActionPerformed);

        jLabel3.setText("NOMBRE DEL CLIENTE");

        jLabel4.setText("DESCRIPCION");

        jLabel5.setText("CANTIDAD");

        jLabel6.setText("PRECIO UNITARIO");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        BtnAgregar.setText("Agregar a Factura");
        BtnAgregar.addActionListener(this::BtnAgregarActionPerformed);

        BtnGuardar.setText("Guardar Factura");
        BtnGuardar.addActionListener(this::BtnGuardarActionPerformed);

        BtnRegresar.setText("Regresar al Menú");
        BtnRegresar.addActionListener(this::BtnRegresarActionPerformed);

        lblTotalGeneral.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblTotalGeneral.setText("Total: Q. 0.00");

        lblFecha.setText("Fecha: 00/00/0000");

        jLabel7.setText("No. Factura: Autogenerado");

        BtnEliminar.setText("Eliminar Producto");
        BtnEliminar.addActionListener(this::BtnEliminarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalGeneral)
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreCliente)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnGuardar)
                        .addGap(85, 85, 85))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblFecha)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 132, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAgregar)
                    .addComponent(BtnRegresar)
                    .addComponent(BtnGuardar)
                    .addComponent(BtnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        FrmMenuPrincipal menu = new FrmMenuPrincipal();
        menu.setVisible(true);
        this.dispose();
    }                                           

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable2.getModel();

// Si la tabla aún no tiene columnas programadas por código, asegúrate de dárselas o crearlas:
if(modelo.getColumnCount() == 0) {
    modelo.addColumn("Descripción");
    modelo.addColumn("Cantidad");
    modelo.addColumn("Precio U.");
    modelo.addColumn("Subtotal");
}

String desc = txtDescripcion.getText();
        int cant = Integer.parseInt(txtCantidad.getText());
        double precio = Double.parseDouble(txtPrecio.getText());
        double subtotal = cant * precio;

modelo.addRow(new Object[]{desc, cant, precio, subtotal});

// Limpiamos campos de producto para agregar otro
txtDescripcion.setText("");
txtCantidad.setText("");
txtPrecio.setText("");

calcularTotalGeneral();
    }                                          

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {                                           
       Factura fac = new Factura();
        fac.setNit(txtNit.getText());
        fac.setNombreCliente(txtNombreCliente.getText());

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable2.getModel();
        
        // Validar que la tabla tenga productos antes de guardar
        if (modelo.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe agregar al menos un producto a la factura.");
            return;
        }

        // Calcular el total general sumando la columna de subtotales (índice 3)
        double totalGeneral = 0;
        for (int i = 0; i < modelo.getRowCount(); i++) {
            totalGeneral += Double.parseDouble(modelo.getValueAt(i, 3).toString());
        }
        fac.setTotal(totalGeneral);

        // 1. Guardar la factura principal y capturar el ID devuelto
        FacturaDAOImpl dao = new FacturaDAOImpl();
        int idFactura = dao.guardarFactura(fac);

        if (idFactura > 0) {
            // 2. Recorrer la tabla visual y guardar cada fila en 'detalle_factura'
            for (int i = 0; i < modelo.getRowCount(); i++) {
                String desc = modelo.getValueAt(i, 0).toString();
                int cant = Integer.parseInt(modelo.getValueAt(i, 1).toString());
                double precio = Double.parseDouble(modelo.getValueAt(i, 2).toString());
                double subtotal = Double.parseDouble(modelo.getValueAt(i, 3).toString());

                dao.guardarDetalle(idFactura, desc, cant, precio, subtotal);
            }

            // 3. Mostramos mensaje de éxito
            javax.swing.JOptionPane.showMessageDialog(this, "¡Factura y detalles guardados correctamente en la Base de Datos!");
            
            // 4. Mostramos el ticket imprimible en pantalla ANTES de borrar los datos
            mostrarFacturaImprimible(fac.getNit(), fac.getNombreCliente(), modelo, totalGeneral);

            // 5. AHORA SÍ, limpiar la tabla y los campos de texto
            modelo.setRowCount(0);
            txtNit.setText("");
            txtNombreCliente.setText("");
            lblTotalGeneral.setText("Total: Q. 0.00");
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar la factura en la base de datos.");
        }
    }                                          

    private void calcularTotalGeneral() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable2.getModel();
        double sumaTotal = 0;
        
        // Recorremos la tabla sumando la columna de subtotales (índice 3)
        for (int i = 0; i < modelo.getRowCount(); i++) {
            sumaTotal += Double.parseDouble(modelo.getValueAt(i, 3).toString());
        }
        
        // Actualizamos el texto de la etiqueta con el total formateado
        lblTotalGeneral.setText("Total: Q. " + String.format("%.2f", sumaTotal));
    }
    
    private void txtNitActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable2.getModel();
        
        // Obtenemos el número de la fila que el usuario seleccionó con un clic
        int filaSeleccionada = jTable2.getSelectedRow();
        
        if (filaSeleccionada >= 0) {
            // Si hay una fila seleccionada, la eliminamos
            modelo.removeRow(filaSeleccionada);
            // Actualizamos el total general para que se reste el producto borrado
            calcularTotalGeneral();
        } else {
            // Si no seleccionó nada, mostramos un mensaje
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione un producto de la tabla para eliminarlo.");
        }
    }                                           

    private void mostrarFacturaImprimible(String nit, String cliente, javax.swing.table.DefaultTableModel modeloTabla, double total) {
        StringBuilder facturaStr = new StringBuilder();
        facturaStr.append("=========================================\n");
        facturaStr.append("           SISTEMA DE FACTURACIÓN        \n");
        facturaStr.append("=========================================\n");
        facturaStr.append(" NIT del Cliente: ").append(nit).append("\n");
        facturaStr.append(" Cliente: ").append(cliente).append("\n");
        facturaStr.append(" -----------------------------------------\n");
        facturaStr.append(String.format(" %-15s %-8s %-8s %-8s\n", "Descripción", "Cant", "Precio", "Subtotal"));
        facturaStr.append(" -----------------------------------------\n");
        
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            String desc = modeloTabla.getValueAt(i, 0).toString();
            String cant = modeloTabla.getValueAt(i, 1).toString();
            String precio = modeloTabla.getValueAt(i, 2).toString();
            String subtotal = modeloTabla.getValueAt(i, 3).toString();
            
            facturaStr.append(String.format(" %-15s %-8s Q.%-7s Q.%-7s\n", desc, cant, precio, subtotal));
        }
        
        facturaStr.append(" -----------------------------------------\n");
        facturaStr.append(String.format(" TOTAL GENERAL: Q. %.2f\n", total));
        facturaStr.append("=========================================\n");
        facturaStr.append("        ¡GRACIAS POR SU COMPRA!          \n");

        // Creamos un área de texto con fuente de tipo consola para que se alinee bien
        javax.swing.JTextArea textArea = new javax.swing.JTextArea(facturaStr.toString());
        textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
        textArea.setEditable(false);

        // Lo metemos en un panel deslizante por si la factura es larga
        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
        scrollPane.setPreferredSize(new java.awt.Dimension(400, 300));

        // Mostramos el diálogo con opción de simular impresión o aceptar
        javax.swing.JOptionPane.showMessageDialog(this, scrollPane, "Factura Generada", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmFactura().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblTotalGeneral;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration                   
}
