/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gt.edu.umg.sistema.estudiantes.vista;

import gt.edu.umg.sistema.estudiantes.controlador.EstudianteController;
import gt.edu.umg.sistema.estudiantes.modelo.Estudiante;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maorozco
 */
public class FrmEstudiante extends javax.swing.JInternalFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmEstudiante.class.getName());

    EstudianteController controller;
    /**
     * Creates new form FrmEstudiante
     */
    public FrmEstudiante() {
        initComponents();
        controller = new EstudianteController(); 
        refrescarTabla();
        
        this.setClosable(true);
    this.setIconifiable(true);
    this.setMaximizable(true);
    this.setResizable(true);
    
    // Línea para asegurar que se cierre correctamente al dar clic en la X
    this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblnombres1 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblnombres2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblnombres3 = new javax.swing.JLabel();
        txtCarnet = new javax.swing.JTextField();
        BtnGrabar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxCarrera = new javax.swing.JComboBox<>();
        chkEstado = new javax.swing.JCheckBox();
        BtnEliminar = new javax.swing.JButton();
        BtnActualizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblnombres.setText("Nombres");

        lblnombres1.setText("Apellidos");

        lblnombres2.setText("email");

        lblnombres3.setText("carnet");

        BtnGrabar.setText("Grabar");
        BtnGrabar.addActionListener(this::BtnGrabarActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellidos", "Email", "Carnet", "Carrera", "Estado"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Carrera");

        jLabel3.setText("Estado");

        cbxCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingeniería en Sistemas", "Ingeniería Industrial", "Arquitectura", "Psicologia ", "Diseñador grafico", " " }));

        chkEstado.setSelected(true);
        chkEstado.setText("Activo");

        BtnEliminar.setText("Eliminiar");
        BtnEliminar.addActionListener(this::BtnEliminarActionPerformed);

        BtnActualizar.setText("Actualizar");
        BtnActualizar.addActionListener(this::BtnActualizarActionPerformed);

        jButton1.setText("Regresar al Menú");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblnombres1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblnombres2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblnombres3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkEstado)
                                    .addComponent(cbxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnGrabar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombres)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombres1)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnombres2)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombres3)
                    .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cbxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(chkEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(BtnActualizar)
                    .addComponent(BtnEliminar)
                    .addComponent(BtnGrabar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void cargarDatosTabla(List<Estudiante> listaEstudiantes) {
    // 1. Definir los encabezados de las columnas
    String[] columnas = {"ID", "Carné", "Nombre", "Apellido", "Correo", "Carrera", "Estado"};
    
    // 2. Crear el modelo (bloqueando la edición directa si lo deseas)
    DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Evita que el usuario edite las celdas directamente
        }
    };

    // 3. Recorrer la lista y agregar cada estudiante como una fila
    for (Estudiante est : listaEstudiantes) {
        Object[] fila = {
           est.getId(),
            est.getCarne(),
            est.getNombre(),
            est.getApellido(),
            est.getEmail(),
            est.getCarrera(),
            est.isEstado() ? "Activo" : "Inactivo" // Muestra un texto amigable para el booleano
        };
        modelo.addRow(fila);
    }

    // 4. Asignar el modelo a tu JTable (reemplaza 'jtEstudiantes' por el nombre de tu variable)
    jTable1.setModel(modelo);
}
    
    private void BtnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGrabarActionPerformed
        // TODO add your handling code here:
        Estudiante estudiante = new Estudiante();
        //estudiante.setId(Integer.parseInt(txtId.getText()));
        estudiante.setNombre(txtNombres.getText());
        estudiante.setApellido(txtApellidos.getText());
        estudiante.setCarne(txtCarnet.getText());
        estudiante.setEmail(txtEmail.getText());
        estudiante.setCarrera(cbxCarrera.getSelectedItem().toString());
        estudiante.setEstado(chkEstado.isSelected());
        
        controller.Guardar(estudiante);   
            
            JOptionPane.showMessageDialog(this, "Estudiante grabado con éxito.");
            
            // Limpiar campos y refrescar los datos mostrados en el JTable
            limpiarCampos();
            refrescarTabla();
        
      cargarDatosTabla(controller.GetEstudiantes());
        
    }//GEN-LAST:event_BtnGrabarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int filaSeleccionada = jTable1.getSelectedRow();
    
    if (filaSeleccionada >= 0) {
        // Suponiendo el orden de tus columnas en la tabla: ID, Carne, Nombre, Apellido, Correo, Carrera, Estado
        txtCarnet.setText(jTable1.getValueAt(filaSeleccionada, 1).toString());
            txtNombres.setText(jTable1.getValueAt(filaSeleccionada, 2).toString());
            txtApellidos.setText(jTable1.getValueAt(filaSeleccionada, 3).toString());
            txtEmail.setText(jTable1.getValueAt(filaSeleccionada, 4).toString());
            cbxCarrera.setSelectedItem(jTable1.getValueAt(filaSeleccionada, 5).toString());
            chkEstado.setSelected(Boolean.parseBoolean(jTable1.getValueAt(filaSeleccionada, 6).toString()));
         }
    }//GEN-LAST:event_jTable1MouseClicked

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        
        if (filaSeleccionada >= 0) {
            Estudiante est = new Estudiante();
            // Tomamos el ID directamente de la columna 0 de la fila seleccionada
            est.setId(Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString()));
            est.setCarne(txtCarnet.getText());
            est.setNombre(txtNombres.getText());
            est.setApellido(txtApellidos.getText());
            est.setEmail(txtEmail.getText());
            est.setCarrera(cbxCarrera.getSelectedItem().toString());
            est.setEstado(chkEstado.isSelected());
        
controller.actualizar(est); // Asegúrate de tener tu instancia del controlador
JOptionPane.showMessageDialog(this, "Estudiante actualizado con éxito.");
            refrescarTabla();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un estudiante de la tabla para actualizar.");
    }//GEN-LAST:event_BtnActualizarActionPerformed
}                                             
    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
      int filaSeleccionada = jTable1.getSelectedRow();
        
        if (filaSeleccionada >= 0) {
            try {
                int id = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
                controller.eliminar(id);
                JOptionPane.showMessageDialog(this, "Estudiante eliminado con éxito.");
                refrescarTabla();
                limpiarCampos();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un estudiante de la tabla para eliminar.");
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrmMenuPrincipal menu = new FrmMenuPrincipal();
    menu.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void limpiarCampos() {
        txtNombres.setText("");
        txtApellidos.setText("");
        txtEmail.setText("");
        txtCarnet.setText("");
    }
    
    private void refrescarTabla() 
    {try {
            // Ajusta 'listar()' por el nombre del método de tu EstudianteController que devuelve la listaList lista = controller.listar();
            cargarDatosTabla(controller.GetEstudiantes());
        } catch (Exception e) {
            logger.severe("No se pudo cargar la lista de estudiantes: " + e.getMessage());
        }}
      
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGrabar;
    private javax.swing.JComboBox<String> cbxCarrera;
    private javax.swing.JCheckBox chkEstado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JLabel lblnombres;
    private javax.swing.JLabel lblnombres1;
    private javax.swing.JLabel lblnombres2;
    private javax.swing.JLabel lblnombres3;
    public javax.swing.JTextField txtApellidos;
    public javax.swing.JTextField txtCarnet;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
